config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'
  resources :questions do

    resources :answers do
      resources :notes do
        put :agree, :disagree
      end
    end
  end

  devise_for :users
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :notes, dependent: :destroy
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  scope :agree, -> { where(agreement: true) }

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :questions
  has_many :answers

# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_question
  before_action :set_answers, only: [:create]
  before_action :set_answer, only: [:edit, :update, :destroy]

  def new
    @answer = @question.answers.build
  end

  def create

    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    authorize @answer
    @answer.save
  end

  private

  def set_answers
    @answers = @question.answers
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:user_id, :question_id, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_question
  before_action :set_answer
  before_action :set_note, only: [:destroy, :agree, :disagree]
  before_action :set_notes, only: [:create]

  def new
    @note = @answer.notes.build
  end

  def create
    @note = @answer.notes.new(note_params)
    authorize @note
    @note.user = current_user
    @note.save
    puts @note.errors.full_messages
  end

  def agree
    @note.update(agreement: true)
    redirect_to questions_path, notice: 'note was successfully agree.'
  end

  def disagree
    @note.update(agreement: false)
    redirect_to questions_path, notice: 'note was successfully disagree.'
  end

  private

  def set_notes
    @notes = @answer.notes
  end

  def set_note
    @note = Note.find(params[:id] || params[:note_id])
  end

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def note_params
    params.require(:note).permit(:user_id, :answer_id, :content)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_questions, only: [:index, :create, :update]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @question = Question.new(params[:question])
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    authorize @question
    @question.save
  end

  def destroy
    authorize @question
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'question was successfully destroyed.' }
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_questions
    @questions = Question.all.order(created_at: :desc)
  end

  def question_params
    params.require(:question).permit(:title, :content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.haml
%p.lead.bg-info{style: 'font-size: 18px'}
  = answer.content
  - answer.notes.agree.each do |note|
    %span{id: "note-#{note.id}"}
      = note.content
  %br
  %u
    = "by #{answer.user.email}"

%div{id: "notes-#{answer.id}"}
  - answer.notes.each do |note|
    = render note

%p
  %div{id: "note-form-#{answer.id}"}
  = link_to 'give a note', new_question_answer_note_path(answer.question, answer), remote: true, class: "btn btn-success active"
%br

app/views/answers/_form.html.haml
= form_for ([@question, @answer]),remote: true, html: { class: 'form-horizontal' }  do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg

    = f.hidden_field :user_id, value: current_user
    = f.hidden_field :question_id, value: @question
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'make the answer', class: "btn btn-primary"
      = link_to 'close', 'javascript:;', class: "btn btn-danger btn-answer-js-close active", data: { question_id: @question.id }

app/views/answers/create.js.erb
$("#answers-<%= @question.id %>").html("<%= j (render @answers) %>");
$('#answer-form').slideUp(350);

app/views/answers/new.html.haml
%h1 New answer
= render 'form'
= link_to 'Back', question_path(@question)

app/views/answers/new.js.erb
$("#answer-form-<%= @question.id %>").html("<%= j (render 'form') %>");
$('#answer-form').slideDown(350);

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Forum"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        .col-lg-6
          .title
            %h1
              = link_to 'Ask us whatever you want', questions_path
        .col-lg-6
          %p.text-right.sign_in
            - if user_signed_in?
              = "Sign in as #{current_user.email}"
              |
              = link_to 'Log out', destroy_user_session_path, :method => :delete
            - else
              = link_to 'Log in', new_user_session_path
              = '//'
              = link_to 'Registration', new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      %footer
        %p &copy; kate2homy@gmail.com 2016

app/views/notes/_form.html.haml
= form_for ([@question, @answer, @note]), remote: true, html: { class: 'form-horizontal' } do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :question_id, value: @question
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'make the note', class: "btn btn-primary"
      = link_to 'close', 'javascript:;', class: "btn btn-danger btn-note-js-close active", data: { answer_id: @answer.id }

app/views/notes/_note.html.haml
%p
  .text-right.lead{style: 'font-size: 16px'}
    = note.content
    %br
    %u
      = "by #{note.user.email}"
    %p
      - if note.agreement
        = link_to "accepted", '#', class: 'accepted', data: { note_id: note.id }
        = "at #{note.updated_at.strftime("%c")}"
      - elsif note.agreement == false
        = "deny at #{note.updated_at.strftime("%c")}"

    %p
      - if current_user == note.answer.user
        = link_to 'agree', question_answer_note_agree_path(note.answer.question, note.answer, note), method: :put
        = link_to 'disagree', question_answer_note_disagree_path(note.answer.question, note.answer, note), method: :put

app/views/notes/create.js.erb
$("#notes-<%= @answer.id %>").html("<%= j (render @notes) %>");
$("#note-form-<%= @answer.id %>").html('');

app/views/notes/new.html.haml
%h1 New correction
= render 'form'
= link_to 'Back', question_path(@question)

app/views/notes/new.js.erb
$("#note-form-<%= @answer.id %>").html("<%= j (render 'form') %>");
$('#note-form').slideDown(350);

app/views/questions/_form.html.haml
= form_for @question, remote: true, html: { class: 'form-horizontal' } do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Make the question', class: "btn btn-primary"
      = link_to 'close', '#', on_click: "$('#question-form').remove()", class: "btn btn-danger active"

app/views/questions/_question.html.haml
%p
  = "Posted on #{question.created_at.strftime("%c")}"
  %u
    = "by #{question.user.email}"
%h3
  = question.title
%p.lead{style: 'font-size: 18px'}
  = question.content
.col-lg-1
.col-lg-11
  %h3
    Answers:
  %div{id: "answers-#{question.id}"}
    = render question.answers
  %p
    %div{id: "answer-form-#{question.id}"}

- if question.user == current_user
  = link_to 'destroy', question_path(question), method: :delete, class: "btn btn-danger active"
= link_to 'give an answer', new_question_answer_path(question), remote: true, class: "btn btn-primary active"
%hr

app/views/questions/create.js.erb
$('#questions').html("<%= j (render @questions) %>");
$('#question-form').slideUp(350);

app/views/questions/index.html.haml
.container
  %h2
    = link_to 'Ask us!', new_question_path, remote: true
  %br
  #question-form
  #questions
    = render @questions

app/views/questions/new.html.haml
%h1 New question
= render 'form'
= link_to 'Back', questions_path

app/views/questions/new.js.erb
$('#question-form').html("<%= j (render 'form') %>");
$('#question-form').slideDown(350);